imports:
    - { resource: settings.yml }

services:
  gitea:
    public:       true
    class:        Gitea\Client
    factory:      Gitea\Client::create
    arguments:    ['%gitea.url%', '%gitea.token%']
    calls:
      - [setPushEventSecret, ['%gitea.pushEventSecret%']]

  baseUrl:
    class:        Acappella\Domain\ValueObject\Url
    arguments:    ['%composer.url%']

  cacheDir:
    class:        Acappella\Domain\ValueObject\Dir
    arguments:    ['%composer.dir%']

  repository:
    class:        Acappella\Domain\Repository
    factory:      Acappella\Domain\Repository::buildFromPath
    arguments:    ['@baseUrl', '@cacheDir', '%composer.dir%/packages.json']

  cache:
    class:        Acappella\Infrastructure\JsonRepositoryCache
    arguments:    ['@repository', 0]

  manager:
    public:       true
    class:        Acappella\Application\GiteaRepositoryManager
    arguments:    ['@cache']
